spring:
  application:
    name: SpringBootStarter
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

